# Autogenerated wrapper script for Silo_jll for aarch64-apple-darwin-mpi+openmpi
export libsilo

using HDF5_jll
using Zlib_jll
using libaec_jll
using OpenMPI_jll
JLLWrappers.@generate_wrapper_header("Silo")
JLLWrappers.@declare_library_product(libsilo, "@rpath/libsiloh5.4.dylib")
function __init__()
    JLLWrappers.@generate_init_header(HDF5_jll, Zlib_jll, libaec_jll, OpenMPI_jll, MPIPreferences)
    JLLWrappers.@init_library_product(
        libsilo,
        "lib/libsiloh5.4.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
