# Autogenerated wrapper script for Silo_jll for armv7l-linux-musleabihf-cxx03-mpi+mpich
export libsilo

using HDF5_jll
using Zlib_jll
using libaec_jll
using MPICH_jll
JLLWrappers.@generate_wrapper_header("Silo")
JLLWrappers.@declare_library_product(libsilo, "libsiloh5.so.4")
function __init__()
    JLLWrappers.@generate_init_header(HDF5_jll, Zlib_jll, libaec_jll, MPICH_jll, MPIPreferences)
    JLLWrappers.@init_library_product(
        libsilo,
        "lib/libsiloh5.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
