# Autogenerated wrapper script for Silo_jll for i686-w64-mingw32-cxx11-mpi+microsoftmpi
export libsilo

using HDF5_jll
using Zlib_jll
using MicrosoftMPI_jll
JLLWrappers.@generate_wrapper_header("Silo")
JLLWrappers.@declare_library_product(libsilo, "libsiloh5.dll")
function __init__()
    JLLWrappers.@generate_init_header(HDF5_jll, Zlib_jll, MicrosoftMPI_jll, MPIPreferences)
    JLLWrappers.@init_library_product(
        libsilo,
        "bin\\libsiloh5.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
